TemStick/Models/CartonLabel.cs
using System.ComponentModel.DataAnnotations;
//using System.Xml.Linq;

namespace TemStick.Models
{
    public class CartonLabel
    {
        public int ID { get; set; }

        [Display(Name = "Carton Number")]
        [Required]
        public int CartonNumber { get; set; }

        [Display(Name = "Buyer Carton Number")]
        [Required]
        public int BuyerCartonNumber { get; set; }

        [Display(Name = "Style PPJ")]
        public string StylePPJ { get; set; }

        [Display(Name = "Brand")]
        public string Brand { get; set; }

        [Display(Name = "Description")]
        public string Description { get; set; }

        [Display(Name = "Fab")]
        public string Fab { get; set; }

        [Display(Name = "Color Name")]
        public string ColorName { get; set; }

        public int Col000 { get; set; }
        public int Col00 { get; set; }
        public int Col0 { get; set; }
        public int Col1 { get; set; }
        public int Col2 { get; set; }
        public int Col3 { get; set; }
        public int Col4 { get; set; }
        public int Col5 { get; set; }
        public int Col6 { get; set; }
        public int Col7 { get; set; }
        public int Col8 { get; set; }
        public int Col9 { get; set; }
        public int Col10 { get; set; }
        public int Col11 { get; set; }
        public int Col12 { get; set; }
        public int Col13 { get; set; }
        public int Col14 { get; set; }
        public int Col15 { get; set; }
        public int Col16 { get; set; }
        public int Col17 { get; set; }
        public int Col18 { get; set; }
        public int Col19 { get; set; }
        public int Col20 { get; set; }
        public int Col21 { get; set; }
        public int Col22 { get; set; }
        public int Col23 { get; set; }
        public int Col24 { get; set; }
        public int Col25 { get; set; }
        public int Col26 { get; set; }
        public int Col27 { get; set; }
        public int Col28 { get; set; }
        public int Col29 { get; set; }
        public int Col30 { get; set; }
        public int Col31 { get; set; }
        public int Col32 { get; set; }
        public int Col33 { get; set; }
        public int Col34 { get; set; }
        public int Col35 { get; set; }
        public int Col36 { get; set; }
        public int Col37 { get; set; }
        public int Col38 { get; set; }
        public int Col39 { get; set; }
        public int Col40 { get; set; }
        public int Col41 { get; set; }
        public int Col42 { get; set; }
        public int Col43 { get; set; }
        public int Col44 { get; set; }
        public int Col45 { get; set; }
        public int Col46 { get; set; }
        public int Col47 { get; set; }
        public int Col48 { get; set; }
        public int Col49 { get; set; }
        public int Col50 { get; set; }
        public int Col51 { get; set; }
        public int Col52 { get; set; }
        public int Col53 { get; set; }
        public int Col54 { get; set; }
        public int Col55 { get; set; }
        public int Col56 { get; set; }
        public int Col57 { get; set; }
        public int Col58 { get; set; }
        public int Col59 { get; set; }
        public int Col60 { get; set; }

        public int Size2XS { get; set; }
        public int SizeXS { get; set; }
        public int SizeS { get; set; }
        public int SizeM { get; set; }
        public int SizeL { get; set; }
        public int SizeXL { get; set; }
        public int Size2XL { get; set; }
        public int Size3XL { get; set; }

        public int SizeX { get; set; }
        public int SizeX1 { get; set; }
        public int SizeX2 { get; set; }
        public int SizeX3 { get; set; }
        public int SizeLL { get; set; }
        public int Size3L { get; set; }
        public int Size4L { get; set; }
        public int Size5L { get; set; }

        [Display(Name = "Total Quantity")]
        [Required]
        public int TotalQuantity { get; set; }

        [Display(Name = "Carton Quantity")]
        [Required]
        public int CartonQuantity { get; set; }

        [Display(Name = "Total Pieces")]
        [Required]
        public int TotalPieces { get; set; }

        [Display(Name = "Total Net Weight")]
        [Required]
        public double TotalNetWeight { get; set; }

        [Display(Name = "Total Gross Weight")]
        [Required]
        public double TotalGrossWeight { get; set; }

        [Display(Name = "Dimension")]
        [Required]
        public string Dimension { get; set; }
    }
}

TemStick/Controllers/CartonLabelsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using TemStick.Data;
using TemStick.Models;
using TemStick.Utilities;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace TemStick.Controllers
{
    public class CartonLabelsController : Controller
    {
        private readonly ShippingContext _context;

        public CartonLabelsController(ShippingContext context)
        {
            _context = context;
        }

        // GET: CartonLabels
        public async Task<IActionResult> Index(string SearchString, int? page, int? pageSizeID, string actionButton, string sortDirection = "asc", string sortField = "Style PPJ")
        {
            var cartons = from c in _context.CartonLabels
                          select c;

            //Clear the sort/filter/paging URL Cookie for Controller
            CookieHelper.CookieSet(HttpContext, ControllerName() + "URL", "", -1);

            //Toggle the Open/Closed state of the collapse depending on if we are filtering
            ViewData["Filtering"] = ""; //Asume not filtering
            //Then in each "test" for filtering, add ViewData["Filtering"] = " show" if true;

            //NOTE: make sure this array has matching values to the column headings
            string[] sortOptions = new[] { "Style PPJ", "Brand" };

            if (!String.IsNullOrEmpty(SearchString))
            {
                cartons = cartons.Where(p => p.StylePPJ.ToUpper().Contains(SearchString.ToUpper())
                                       || p.Brand.ToUpper().Contains(SearchString.ToUpper()));
                ViewData["Filtering"] = " show";
            }

            //Before we sort, see if we have called for a change of filtering or sorting
            if (!String.IsNullOrEmpty(actionButton)) //Form Submitted!
            {
                page = 1;//Reset page to start

                if (sortOptions.Contains(actionButton))//Change of sort is requested
                {
                    //Reverse order on same field
                    if (actionButton == sortField) sortDirection = sortDirection == "asc" ? "desc" : "asc";
                    sortField = actionButton;//Sort by the button clicked
                }
            }
            //Now we know which field and direction to sort by
            if (sortField == "Brand")
            {
                cartons = sortDirection == "asc" ? cartons.OrderBy(p => p.Brand).ThenBy(p => p.StylePPJ) : cartons = cartons.OrderByDescending(p => p.Brand).ThenByDescending(p => p.StylePPJ);
            }
            else //Sorting by Last Name
            {
                cartons = sortDirection == "asc" ? cartons.OrderBy(p => p.StylePPJ).ThenBy(p => p.Brand) : cartons.OrderByDescending(p => p.StylePPJ).ThenByDescending(p => p.Brand);
            }
            //Set sort for next time
            ViewData["sortField"] = sortField;
            ViewData["sortDirection"] = sortDirection;

            //Handle Paging
             int pageSize = PageSizeHelper.SetPageSize(HttpContext, pageSizeID);
            ViewData["pageSizeID"] = PageSizeHelper.PageSizeList(pageSize);

            var pagedData = await PaginatedList<CartonLabel>.CreateAsync(cartons.AsNoTracking(), page ?? 1, pageSize);

            return View(pagedData);
        }

        // GET: CartonLabels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            //URL with the last filter, sort and page parameters for this controller
            ViewDataReturnURL();

            if (id == null || _context.CartonLabels == null) NotFound();

            var cartonLabel = await _context.CartonLabels.FirstOrDefaultAsync(m => m.ID == id);

            if (cartonLabel == null) NotFound();

            List<string> names = new List<string>();
            List<int> values = new List<int>();

            void SetNamesAndValues(string n, int v)
            {
                names.Add(n);
                values.Add(v);
            }

            if (cartonLabel.Col000 != 0) SetNamesAndValues("000", cartonLabel.Col000);
            if (cartonLabel.Col00 != 0) SetNamesAndValues("00", cartonLabel.Col00);
            for (int i = 0; i <= 60; i++)
            {
                var prop = typeof(CartonLabel).GetProperty($"Col{i}");
                int objInt = (int)prop.GetValue(cartonLabel, null);
                if (objInt != 0)
                {
                    names.Add($"{i}");
                    values.Add(objInt);
                }
            }

            var sizes = new List<(string n, int v)>{
                ("XXS", cartonLabel.Size2XS),
                ("XS", cartonLabel.SizeXS),
                ("S", cartonLabel.SizeS),
                ("M", cartonLabel.SizeM),
                ("L", cartonLabel.SizeL),
                ("XL", cartonLabel.SizeXL),
                ("XXL", cartonLabel.Size2XL),
                ("3XL", cartonLabel.Size3XL),
                ("X1", cartonLabel.SizeX1),
                ("X2", cartonLabel.SizeX2),
                ("X3", cartonLabel.SizeX3),
                ("LL", cartonLabel.SizeLL),
                ("3L", cartonLabel.Size3L),
                ("4L", cartonLabel.Size4L),
                ("5L", cartonLabel.Size5L)
            };

            foreach (var size in sizes)
            {
                if (size.v != 0) SetNamesAndValues(size.n, size.v);
            }

            ViewData["Names"] = names;
            ViewData["Values"] = values;

            return View(cartonLabel);
        }

        // GET: CartonLabels/Create
        public IActionResult Create()
        {
            //URL with the last filter, sort and page parameters for this controller
            ViewDataReturnURL();
            return View();
        }

        // POST: CartonLabels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,CartonNumber,BuyerCartonNumber, StylePPJ,Brand,Description,Fab,ColorName," +
            "Col000,Col00,Col0,Col1,Col2,Col3,Col4,Col5,Col6,Col7,Col8,Col9,Col10," +
            "Col11,Col12,Col13,Col14,Col15,Col16,Col17,Col18,Col19,Col20," +
            "Col21,Col22,Col23,Col24,Col25,Col26,Col27,Col28,Col29,Col30," +
            "Col31,Col32,Col33,Col34,Col35,Col36,Col37,Col38,Col39,Col40," +
            "Col41,Col42,Col43,Col44,Col45,Col46,Col47,Col48,Col49,Col50," +
            "Col51,Col52,Col53,Col54,Col55,Col56,Col57,Col58,Col59,Col60," +
            "Size2XS,SizeXS,SizeS,SizeM,SizeL,SizeXL,Size2XL,Size3XL,SizeX1,SizeX2,SizeX3,SizeLL,Size3L,Size4L,Size5L," +
            "TotalQuantity,CartonQuantity,TotalPieces,TotalNetWeight,TotalGrossWeight,Dimension")] CartonLabel cartonLabel)
        {
            //URL with the last filter, sort and page parameters for this controller
            ViewDataReturnURL();

            if (ModelState.IsValid)
            {
                _context.Add(cartonLabel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cartonLabel);
        }

        // GET: CartonLabels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            //URL with the last filter, sort and page parameters for this controller
            ViewDataReturnURL();

            if (id == null || _context.CartonLabels == null) NotFound();

            var cartonLabel = await _context.CartonLabels.FindAsync(id);
            if (cartonLabel == null) NotFound();
            return View(cartonLabel);
        }

        // POST: CartonLabels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id)
        {
            //URL with the last filter, sort and page parameters for this controller
            ViewDataReturnURL();

            var labelToUpdate = await _context.CartonLabels.SingleOrDefaultAsync(l => l.ID == id);

            if (labelToUpdate == null) NotFound();

            if (await TryUpdateModelAsync(labelToUpdate, "", l => l.CartonNumber, l => l.BuyerCartonNumber, l => l.StylePPJ, l => l.Brand, l => l.Description, l => l.Fab, l => l.ColorName,
                l => l.Col00, l => l.Col0, l => l.Col1, l => l.Col2, l => l.Col3, l => l.Col4, l => l.Col5, l => l.Col6, l => l.Col7, l => l.Col8, l => l.Col9, l => l.Col10,
                l => l.Col11, l => l.Col12, l => l.Col13, l => l.Col14, l => l.Col15, l => l.Col16, l => l.Col17, l => l.Col18, l => l.Col19, l => l.Col20,
                l => l.Col21, l => l.Col22, l => l.Col23, l => l.Col24, l => l.Col25, l => l.Col26, l => l.Col27, l => l.Col28, l => l.Col29, l => l.Col30,
                l => l.Col31, l => l.Col32, l => l.Col33, l => l.Col34, l => l.Col35, l => l.Col36, l => l.Col37, l => l.Col38, l => l.Col39, l => l.Col40,
                l => l.Col41, l => l.Col42, l => l.Col43, l => l.Col44, l => l.Col45, l => l.Col46, l => l.Col47, l => l.Col48, l => l.Col49, l => l.Col50,
                l => l.Col51, l => l.Col52, l => l.Col53, l => l.Col54, l => l.Col55, l => l.Col56, l => l.Col57, l => l.Col58, l => l.Col59, l => l.Col60,
                l => l.Size2XS, l => l.SizeXS, l => l.SizeS, l => l.SizeM, l => l.SizeL, l => l.SizeXL, l => l.Size2XL, l => l.Size3XL,
                l => l.SizeX1, l => l.SizeX2, l => l.SizeX3, l => l.SizeLL, l => l.Size3L, l => l.Size4L, l => l.Size5L,

TemStick/Views/CartonLabels/Delete.cshtml
@model TemStick.Models.CartonLabel

@{
    ViewData["Title"] = "Delete";
    var names = (List<string>)ViewData["Names"];
    var values = (List<int>)ViewData["Values"]; 
}

<h1>Are you sure you want to delete this?</h1>


<div class="transition_container">
    <hr />
    <dl class="row">
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.CartonNumber)
        </dt>
        <dd class="col-sm-8">
            @Html.DisplayFor(model => model.CartonNumber)
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.BuyerCartonNumber)
        </dt>
        <dd class="col-sm-8">
            @Html.DisplayFor(model => model.BuyerCartonNumber)
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.StylePPJ)
        </dt>
        <dd class="col-sm-8">
            @Html.DisplayFor(model => model.StylePPJ)
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.Brand)
        </dt>
        <dd class="col-sm-8">
            @Html.DisplayFor(model => model.Brand)
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-8">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.Fab)
        </dt>
        <dd class="col-sm-8">
            @Html.DisplayFor(model => model.Fab)
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.ColorName)
        </dt>
        <dd class="col-sm-8">
            @Html.DisplayFor(model => model.ColorName)
        </dd>
        <dt class="col-sm-4">
            Sizes
        </dt>
        <dd class="col-sm-8">
            @*table for sizes for better view
            results with 0 are filtered*@
            <table class="table table-striped table-bordered table-responsive">
                <tr>
                    @for (int i = 0; i < values.Count(); i++)
                    {
                        <th>@names.ElementAt(i)</th>
                    }
                </tr>
                <tr>
                    @for (int i = 0; i < values.Count(); i++)
                    {
                        <td>@values.ElementAt(i)</td>
                    }
                </tr>
            </table>
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.TotalQuantity)
        </dt>
        <dd class="col-sm-8">
            @Html.DisplayFor(model => model.TotalQuantity)
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.CartonQuantity)
        </dt>
        <dd class="col-sm-8">
            @Html.DisplayFor(model => model.CartonQuantity)
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.TotalPieces)
        </dt>
        <dd class="col-sm-8">
            @Html.DisplayFor(model => model.TotalPieces)
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.TotalNetWeight)
        </dt>
        <dd class="col-sm-8">
            @Html.DisplayFor(model => model.TotalNetWeight)
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.TotalGrossWeight)
        </dt>
        <dd class="col-sm-8">
            @Html.DisplayFor(model => model.TotalGrossWeight)
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.Dimension)
        </dt>
        <dd class="col-sm-8">
            @Html.DisplayFor(model => model.Dimension)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a href='@ViewData["returnURL"]'>Back to List</a>
    </form>
</div>

TemStick/Views/CartonLabels/Details.cshtml
@model TemStick.Models.CartonLabel

@{
    ViewData["Title"] = "Details";
    var names = (List<string>)ViewData["Names"];
    var values = (List<int>)ViewData["Values"];
}

<h1>Label Details</h1>

<div class="transition_container">
    <div>
        <hr />
        <dl class="row">
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.CartonNumber)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.CartonNumber)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.BuyerCartonNumber)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.BuyerCartonNumber)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.StylePPJ)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.StylePPJ)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.Brand)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.Brand)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.Description)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.Fab)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.Fab)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.ColorName)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.ColorName)
            </dd>
            <dt class="col-sm-4">
                Sizes
            </dt>
            <dd class="col-sm-8">
                @*table for sizes for better view
                results with 0 are filtered*@
                <table class="table table-striped table-bordered table-responsive">
                    <tr>
                        @for (int i = 0; i < values.Count(); i++)
                        {
                            <th>@names.ElementAt(i)</th>
                        }
                    </tr>
                    <tr>
                        @for (int i = 0; i < values.Count(); i++)
                        {
                            <td>@values.ElementAt(i)</td>
                        }
                    </tr>
                </table>
            </dd>
            <dt class = "col-sm-4">
                @Html.DisplayNameFor(model => model.TotalQuantity)
            </dt>
            <dd class = "col-sm-8">
                @Html.DisplayFor(model => model.TotalQuantity)
            </dd>
            <dt class = "col-sm-4">
                @Html.DisplayNameFor(model => model.CartonQuantity)
            </dt>
            <dd class = "col-sm-8">
                @Html.DisplayFor(model => model.CartonQuantity)
            </dd>
            <dt class = "col-sm-4">
                @Html.DisplayNameFor(model => model.TotalPieces)
            </dt>
            <dd class = "col-sm-8">
                @Html.DisplayFor(model => model.TotalPieces)
            </dd>
            <dt class = "col-sm-4">
                @Html.DisplayNameFor(model => model.TotalNetWeight)
            </dt>
            <dd class = "col-sm-8">
                @Html.DisplayFor(model => model.TotalNetWeight)
            </dd>
            <dt class = "col-sm-4">
                @Html.DisplayNameFor(model => model.TotalGrossWeight)
            </dt>
            <dd class = "col-sm-8">
                @Html.DisplayFor(model => model.TotalGrossWeight)
            </dd>
            <dt class = "col-sm-4">
                @Html.DisplayNameFor(model => model.Dimension)
            </dt>
            <dd class = "col-sm-8">
                @Html.DisplayFor(model => model.Dimension)
            </dd>
        </dl>
    </div>
    <div>
        <a asp-action="Edit" asp-route-id="@Model?.ID">Edit</a> |
        <a href='@ViewData["returnURL"]'>Back to List</a>
    </div>
</div>

TemStick/Views/CartonLabels/Index.cshtml
@model IEnumerable<TemStick.Models.CartonLabel>

@{
    ViewData["Title"] = "Index";
}



<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<p class="text-danger">@TempData["Message"]</p>
<p class="text-success">@TempData["Success"]</p>

<div class="transition_container">
    <div class="row m-0">
        <div class="card mb-3 mr-3 shadow mb-5 bg-body rounded">
            <div class="card-header"></div>
            <div class="card-body">
                <form asp-action="DownloadLabels" asp-controller="CartonLabels" method="post" enctype="multipart/form-data">
                    <h5 class="card-title">Get Labels</h5>
                    <p class="card-text">Download the entire page into a customized excel spreadsheet.</p>
                    <input type="submit" value="Download" class="btn btn-primary" />
                </form>
            </div>
        </div>
        <div class="card mb-3 mr-3 shadow mb-5 bg-body rounded">
            <div class="card-header"></div>
            <div class="card-body">
                <form asp-action="InsertFromExcel" asp-controller="CartonLabels" method="post" enctype="multipart/form-data">
                    <h5 class="card-title">Upload Excel File:</h5>
                    <p class="card-text"><input type="file" class="card-text" name="theExcel" /></p>
                    <input type="submit" value="Upload Data ↑" class="btn btn-success" />
                    <a href="~/example_excel/upload_template.xlsx">View Upload Template</a>
                </form>
            </div>
        </div>
    </div>

    <form asp-action="Index" method="get">
        <input type="hidden" name="sortDirection" value="@ViewData["sortDirection"]" />
        <input type="hidden" name="sortField" value="@ViewData["sortField"]" />
        <div class="form-horizontal">
            <button class="btn btn-outline-secondary" type="button" data-toggle="collapse" id="filterToggle" data-target="#collapseFilter" aria-expanded="false" aria-controls="collapseFilter">
                Filter/Search
            </button>
            <div class="collapse @(ViewData["Filtering"])" id="collapseFilter">
                <div class="card card-body bg-light">
                    <div class="row">
                        <div class="form-group col-md-4">
                            <label class="control-label">Search Coach Name:</label>
                            @Html.TextBox("SearchString", null, new { @class = "form-control" })
                        </div>
                        <div class="form-group col-md-4 align-self-end">
                            <input type="submit" name="actionButton" value="Filter" class="btn btn-outline-primary" />
                            <a asp-action="Index" class="btn btn-outline-dark">Clear</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="d-block d-lg-none">
            <div class="card-deck-wrapper">
                <div class="card-deck">
                    <div class="card mb-sm-3 shadow mb-5 bg-body rounded" style="min-width: 18rem;">
                        <div class="card-header"></div>
                        <div class="card-body">
                            <form asp-action="DeleteAll" asp-controller="CartonLabels" method="post" enctype="multipart/form-data">
                                <h5 class="card-title">Mass Delete</h5>
                                <p class="card-text">Remove all records of of the current page.</p>
                                <button type="submit" value="Delete" class="btn btn-danger" onclick="return confirm('This action will delete all records. Are you willing to proceed? ')">
                                    @*<i class="fa fa-trash-o"></i> *@Delete All
                                </button>
                            </form>
                        </div>
                    </div>
                    @foreach (var item in Model)
                    {
                        <div class="card mb-sm-3" style="min-width: 18rem;">
                            <h5 class="card-header"><strong>@Html.DisplayFor(modelItem => item.Brand)</strong></h5>
                            <div class="card-body">
                                <div class="media-body">
                                    <p class="card-text">
                                        <strong>Carton Number:</strong> @Html.DisplayFor(modelItem => item.CartonNumber)<br />
                                        <strong>Buyer Carton Number:</strong> @Html.DisplayFor(modelItem => item.BuyerCartonNumber)<br />
                                        <strong>Description:</strong> @Html.DisplayFor(modelItem => item.Description)<br />
                                    </p>
                                    <div class="card-footer">
                                        <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                                        <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                                        <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>

        <table class="table d-none d-lg-block">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.CartonNumber)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.BuyerCartonNumber)
                    </th>
                    <th>
                        <input type="submit" name="actionButton" value="Style PPJ" class="btn btn-link" />
                    </th>
                    <th>
                        <input type="submit" name="actionButton" value="Brand" class="btn btn-link" />
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Description)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ColorName)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model) {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.CartonNumber)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.BuyerCartonNumber)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.StylePPJ)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Brand)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ColorName)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                            <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                            <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <partial name="_PagingNavBar" />
    </form>
    <form asp-action="DeleteAll" asp-controller="CartonLabels">
        <div class="d-none d-lg-block">
            <button type="submit" value="Delete" class="btn btn-danger" onclick="return confirm('This action will delete all records. Are you willing to proceed? ')">
                @*<i class="fa fa-trash-o"></i> *@Delete All
            </button>
        </div>
    </form>
    </div>